export enum WebimNativeErrorType {
  'NULL_SESSION' = 'NULL_SESSION',
  'WRONG_SESSION' = 'WRONG_SESSION',
  'UNKNOWN' = 'UNKNOWN',
  'NULL_ACCOUNT_NAME' = 'NULL_ACCOUNT_NAME',
  'NULL_LOCATION' = 'NULL_LOCATION',
  'INVALID_AUTHENTIFICATOR_PARAMETERS' = 'INVALID_AUTHENTIFICATOR_PARAMETERS',
  'INVALID_REMOTE_NOTIFICATION_CONFIGURATION' = 'INVALID_REMOTE_NOTIFICATION_CONFIGURATION',
  'INVALID_HEX' = 'INVALID_HEX',
  'NO_NETWORK_CONNECTION' = 'NO_NETWORK_CONNECTION',
  'SOCKET_TIMEOUT_EXPIRED' = 'SOCKET_TIMEOUT_EXPIRED',
  'SERVER_CONNECTED' = 'SERVER_CONNECTED',
  'SERVER_DISCONNECTED' = 'SERVER_DISCONNECTED',
  'FILE_SIZE_EXCEEDED' = 'FILE_SIZE_EXCEEDED',
  'FILE_SIZE_TOO_SMALL' = 'FILE_SIZE_TOO_SMALL',
  'FILE_TYPE_NOT_ALLOWED' = 'FILE_TYPE_NOT_ALLOWED',
  'MAX_FILES_COUNT_PER_CHAT_EXCEEDED' = 'MAX_FILES_COUNT_PER_CHAT_EXCEEDED',
  'UPLOADED_FILE_NOT_FOUND' = 'UPLOADED_FILE_NOT_FOUND',
  'UNAUTHORIZED' = 'UNAUTHORIZED',
  'NO_CHAT' = 'NO_CHAT',
  'NOTE_IS_TOO_LONG' = 'NOTE_IS_TOO_LONG',
  'OPERATOR_NOT_INT_CHAT' = 'OPERATOR_NOT_INT_CHAT',
  'ACCOUNT_BLOCKED' = 'ACCOUNT_BLOCKED',
  'PROVIDED_VISITOR_EXPIRED' = 'PROVIDED_VISITOR_EXPIRED',
  'VISITOR_BANNED' = 'VISITOR_BANNED',
  'WRONG_PROVIDED_VISITOR_HASH' = 'WRONG_PROVIDED_VISITOR_HASH'
}

export type CustomWebimNativeError = string;
